security:
    encoders: 
        App\Entity\Usuario: { algorithm: bcrypt , cost: 13 }

    role_hierarchy:
       # ROLE_SUPERADMIN:  ROLE_ADMIN
        ROLE_ADMIN:  [ROLE_CAJERO, ROLE_JEFETRANSPORTE, ROLE_ELECTRICIDAD]


    providers:
        usuarios:
            entity: { class: App:Usuario}


    firewalls:
        secured_area:
            pattern:    ^/*
            user_checker: App\Security\UserChecker
            form_login:
                login_path: index
                check_path: check
                default_target_path: index
                always_use_default_target_path: true
            logout:
                path:   logout
                target: index
            anonymous: ~
            remember_me:
                secret:  '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week in seconds
                path: index
    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/estatica/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #rutas de superadmin
        - { path: ^/provincia, roles: ROLE_SUPERADMIN }
        - { path: ^/institucion, roles: ROLE_SUPERADMIN }
        - { path: ^/municipio, roles: ROLE_SUPERADMIN }
        - { path: ^/tipocombustible, roles: ROLE_SUPERADMIN }
        - { path: ^/tipovehiculo, roles: ROLE_SUPERADMIN }
        - { path: ^/tarifakw, roles: ROLE_SUPERADMIN }
        - { path: ^/cupet, roles: ROLE_SUPERADMIN }
        - { path: ^/licencia, roles: ROLE_SUPERADMIN }
        - { path: ^/preciocombustible/findbytarjeta, roles: ROLE_CAJERO }
        - { path: ^/preciocombustible/findbyvehiculo, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/preciocombustible, roles: ROLE_SUPERADMIN }
        - { path: ^/tabladistancia/new,  roles: ROLE_SUPERADMIN }
        - { path: ^/tabladistancia/\d+/edit,  roles: ROLE_SUPERADMIN }
        - { path: ^/tabladistancia/\d+/delete,  roles: ROLE_SUPERADMIN }
        #Rutas de administracion
        - { path: ^/centrocosto/\d+/searchbycuenta, roles: ROLE_ELECTRICIDAD }
        - { path: ^/centrocosto, roles: ROLE_ADMIN }
        - { path: ^/cuenta, roles: ROLE_ADMIN }
        - { path: ^/partida, roles: ROLE_ADMIN }
        - { path: ^/reloj, roles: ROLE_ADMIN }
        - { path: ^/tipoactividad, roles: ROLE_ADMIN }
        - { path: ^/tipotarjeta, roles: ROLE_ADMIN }
        - { path: ^/area/\d+/findbyinstitucion, roles: ROLE_CAJERO }
        - { path: ^/area, roles: ROLE_ADMIN }
        - { path: ^/elemento/\d+/searchbypartida, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/elemento, roles: ROLE_ADMIN }
        - { path: ^/subelemento/\d+/searchbycuenta, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/subelemento, roles: ROLE_ADMIN }
        - { path: ^/subelemento/\d+/searchbycuenta, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/subelemento, roles: ROLE_ADMIN }
        - { path: ^/usuario/\d+/show, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/usuario/\d+/edit, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/usuario, roles: [ROLE_SUPERADMIN, ROLE_ADMIN] }
        #Rutas de transporte
        - { path: ^/tabladistancia$, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/chofer/new, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/chofer, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/vehiculo/new, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/vehiculo, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/mantenimiento, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/reparacion, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/hojaruta, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/pruebalitro, roles: ROLE_JEFETRANSPORTE }
        #Rutas de cajero
        - { path: ^/tarjeta/\d+/findbyinstitucion, roles: ROLE_CAJERO }
        - { path: ^/tarjeta, roles: ROLE_CAJERO }
        - { path: ^/chip, roles: ROLE_CAJERO }
        - { path: ^/recargatarjeta, roles: ROLE_CAJERO }
        - { path: ^/ajustetarjeta, roles: ROLE_CAJERO }
        - { path: ^/cierremescombustible, roles: ROLE_CAJERO }
        - { path: ^/cierremestarjeta, roles: ROLE_CAJERO }
        - { path: ^/responsable/\d+/findbyinstitucion, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/responsable, roles:  ROLE_CAJERO }
        #Rutas de electricidad
        - { path: ^/recargakw, roles: ROLE_ELECTRICIDAD }
        - { path: ^/lecturareloj, roles: ROLE_ELECTRICIDAD }
        - { path: ^/cierremeskw, roles: ROLE_ELECTRICIDAD }
        - { path: ^/cierremesarea, roles: ROLE_ELECTRICIDAD }
        - { path: ^/planportadores, roles: ROLE_ELECTRICIDAD }
        - { path: ^/planportadoresarea, roles: ROLE_ELECTRICIDAD }
        - { path: ^/planefectivo, roles: ROLE_ELECTRICIDAD }
        - { path: ^/planefectivocuenta, roles: ROLE_ELECTRICIDAD }
        #Se protejen el resto de las ruta
        - { path: ^/*, roles: IS_AUTHENTICATED_FULLY }


