security:
    encoders: 
        App\Entity\Usuario: { algorithm: bcrypt , cost: 13 }

    role_hierarchy:
        ROLE_SUPERADMIN:  ROLE_ADMIN
        ROLE_ADMIN:  [ROLE_CAJERO, ROLE_JEFETRANSPORTE, ROLE_ELECTRICIDAD]


    providers:
        usuarios:
            entity: { class: App:Usuario}


    firewalls:
        secured_area:
            pattern:    ^/*
            user_checker: App\Security\UserChecker
            form_login:
                login_path: index
                check_path: check
                default_target_path: index
                always_use_default_target_path: true
            logout:
                path:   logout
                target: index
            anonymous: ~
            remember_me:
                secret:  '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week in seconds
                path: index
    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/estatica/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #Rutas de administracion
        - { path: ^/provincia, roles: ROLE_ADMIN }
        - { path: ^/municipio, roles: ROLE_ADMIN }
        - { path: ^/centrocosto, roles: ROLE_ADMIN }
        - { path: ^/cuenta, roles: ROLE_ADMIN }
        - { path: ^/partida, roles: ROLE_ADMIN }
        - { path: ^/reloj, roles: ROLE_ADMIN }
        - { path: ^/cupet, roles: ROLE_ADMIN }
        - { path: ^/tipoactividad, roles: ROLE_ADMIN }
        - { path: ^/tipocombustible, roles: ROLE_ADMIN }
        - { path: ^/tipotarjeta, roles: ROLE_ADMIN }
        - { path: ^/tipovehiculo, roles: ROLE_ADMIN }
        - { path: ^/tarifakw, roles: ROLE_ADMIN }
        - { path: ^/area, roles: ROLE_ADMIN }
        - { path: ^/licencia, roles: ROLE_ADMIN }
        - { path: ^/elemento\d+/searchbypartida, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/elemento, roles: ROLE_ADMIN }
        - { path: ^/subelemento\d+/searchbycuenta, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/subelemento, roles: ROLE_ADMIN }
        - { path: ^/subelemento\d+/searchbycuenta, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/subelemento, roles: ROLE_ADMIN }
        - { path: ^/usuario$, roles: ROLE_ADMIN }
        - { path: ^/usuario/new, roles: ROLE_ADMIN }
        - { path: ^/usuario\d+/delete, roles: ROLE_ADMIN }
        - { path: ^/usuario$, roles: IS_AUTHENTICATED_FULLY }
        #Rutas de transporte
        - { path: ^/chofer, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/responsable, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/vehiculo, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/mantenimiento, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/reparacion, roles: ROLE_JEFETRANSPORTE }
        - { path: ^/hojaruta, roles: ROLE_JEFETRANSPORTE }
        #Rutas de cajero
        - { path: ^/tarjeta, roles: ROLE_CAJERO }
        - { path: ^/chip, roles: ROLE_CAJERO }
        - { path: ^/recargatarjeta, roles: ROLE_CAJERO }
        - { path: ^/ajustetarjeta, roles: ROLE_CAJERO }
        - { path: ^/cierremescombustible, roles: ROLE_CAJERO }
        - { path: ^/cierremestarjeta, roles: ROLE_CAJERO }
        - { path: ^/planportadores, roles: ROLE_CAJERO }
        - { path: ^/planportadoresarea, roles: ROLE_CAJERO }
        - { path: ^/planefectivo, roles: ROLE_CAJERO }
        - { path: ^/planefectivocuenta, roles: ROLE_CAJERO }
        - { path: ^/preciocombustible, roles: ROLE_CAJERO }
        #Rutas de electricidad
        - { path: ^/recargakw, roles: ROLE_ELECTRICIDAD }
        - { path: ^/lecturareloj, roles: ROLE_ELECTRICIDAD }
        - { path: ^/cierremeskw, roles: ROLE_ELECTRICIDAD }
        - { path: ^/cierremesarea, roles: ROLE_ELECTRICIDAD }
        #Se protejen el resto de las ruta
       # - { path: ^/*, roles: IS_AUTHENTICATED_FULLY }


